[package]
name = "aoc2022"
version = "0.0.0"
edition = "2021"

[dependencies]
indicatif = "0.17.2"
itertools = "0.10.5"
rayon = "1.6.1"
regex = "1.7.0"
serde = { version = "1.0.150", features = ["derive"] }
serde_json = "1.0.89"
